### ISSUE TITLE
MSPDI export crashes with Java 9 and Java 10

### ISSUE THREAD

**Issue by lathiere** [bardsoftware/ganttproject#1534]
A Java Exception crashs the export: **javax/xml/JAXBException**
 Here is the log:

```
GanttProject 2.8.7 Pilsen (build 2262)
Settings file:
	location: C:\Users\Benoit Lathiere\.ganttproject
	size:5239
	is readable: true
java.class.path: eclipsito.jar;C:\Program Files (x86)\GanttProject-2.8
java.home: C:\Program Files\Java\jre-10.0.1
java.ext.dirs: null
java.io.tmpdir: C:\Users\BENOIT~1\AppData\Local\Temp\
java.runtime.version: 10.0.1+10
java.vendor: Oracle Corporation
java.vm.name: Java HotSpot(TM) 64-Bit Server VM
java.vm.vendor: "Oracle Corporation"
java.vm.version: 10.0.1+10
os.arch: amd64
os.name: Windows 10
os.version: 10.0
sun.java.command: org.bardsoftware.eclipsito.Boot ganttproject-eclipsito-config.xml -log true
user.country: FR
user.dir: C:\Program Files (x86)\GanttProject-2.8
user.home: C:\Users\Benoit Lathiere
user.language: fr
user.timezone: Europe/Paris

avr. 25, 2018 10:54:07 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Options file:C:\Users\Benoit Lathiere\.ganttproject
avr. 25, 2018 10:54:08 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Waiting until main window closes
avr. 25, 2018 10:54:08 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Deleting old auto-save files
Creating main frame...
1. loading look'n'feels
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
2. loading options
3. creating menus...
4. creating views...
5. calculating size and packing...
6. changing language ...
7. first attempt to restore bounds
avr. 25, 2018 10:54:14 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Bounds stored in the  options: java.awt.Rectangle[x=-1928,y=-8,width=1936,height=1096]
8. finalizing...
Main frame created
avr. 25, 2018 10:54:14 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Bounds after setVisible: java.awt.Rectangle[x=-1928,y=-8,width=1936,height=1096]
Splash closed
avr. 25, 2018 10:54:14 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Starting RSS check...
Resizing window...
avr. 25, 2018 10:54:15 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Bounds after opening: java.awt.Rectangle[x=-1928,y=-8,width=1936,height=1096]
avr. 25, 2018 10:54:15 AM net.sourceforge.ganttproject.GPLogger log
INFOS: Bounds stored in the  options: java.awt.Rectangle[x=-1928,y=-8,width=1936,height=1096]
avr. 25, 2018 10:54:17 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFOS: Scanning font directories...
avr. 25, 2018 10:54:17 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=C:\Program Files\Java\jre-10.0.1/lib/fonts
avr. 25, 2018 10:54:17 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=C:/windows/fonts
avr. 25, 2018 10:54:19 AM net.sourceforge.ganttproject.GPLogger log
INFOS: RSS check finished
avr. 25, 2018 10:54:32 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=/usr/share/fonts/truetype
avr. 25, 2018 10:54:32 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: directory /usr/share/fonts/truetype is not readable
avr. 25, 2018 10:54:32 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=/System/Library/Fonts
avr. 25, 2018 10:54:32 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: directory /System/Library/Fonts is not readable
avr. 25, 2018 10:54:32 AM org.ganttproject.impex.htmlpdf.fonts.TTFontCache registerDirectory
INFOS: scanning directory=/C:/Program Files (x86)/GanttProject-2.8/plugins-2.8.7/org.ganttproject.impex.htmlpdf/resource/fonts
avr. 25, 2018 10:54:33 AM org.ganttproject.impex.htmlpdf.itext.ITextEngine$2 run
INFOS: Scanning font directories completed
no editor for column=0 class=interface javax.swing.Icon
no editor for column=1 class=interface javax.swing.Icon
no editor for column=2 class=interface javax.swing.Icon
avr. 25, 2018 10:57:50 AM net.sourceforge.ganttproject.parser.HolidayTagHandler loadHoliday
AVERTISSEMENT: Error when parsing calendar data. Raw data: com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$AttributesProxy@37c66c35
java.lang.NumberFormatException: For input string: "S"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at net.sourceforge.ganttproject.parser.HolidayTagHandler.loadHoliday(HolidayTagHandler.java:115)
	at net.sourceforge.ganttproject.parser.HolidayTagHandler.endElement(HolidayTagHandler.java:71)
	at net.sourceforge.ganttproject.io.XmlParser.endElement(XmlParser.java:88)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at java.xml/javax.xml.parsers.SAXParser.parse(Unknown Source)
	at net.sourceforge.ganttproject.io.XmlParser.parse(XmlParser.java:110)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.doLoad(GanttXMLOpen.java:102)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.load(GanttXMLOpen.java:96)
	at net.sourceforge.ganttproject.document.ProxyDocument$ParsingState.enter(ProxyDocument.java:360)
	at net.sourceforge.ganttproject.document.ProxyDocument.read(ProxyDocument.java:178)
	at net.sourceforge.ganttproject.GanttProject.open(GanttProject.java:689)
	at net.sourceforge.ganttproject.gui.ProjectOpenStrategy.openFileAsIs(ProjectOpenStrategy.java:119)
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:248)
	at net.sourceforge.ganttproject.action.project.OpenMRUDocumentAction.actionPerformed(OpenMRUDocumentAction.java:66)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

scheduling job=net.sourceforge.ganttproject.export.ExporterBase$2@11e6b871 group=net.sourceforge.ganttproject.gui.GanttStatusBar$ProgressMonitorImpl@13394b21
scheduling job=net.sourceforge.ganttproject.export.ExporterBase$2@11e6b871
avr. 25, 2018 10:58:04 AM net.sourceforge.ganttproject.GPLogger log
INFOS: [ProgressMonitorImpl] begin Task: name=Running export
avr. 25, 2018 10:58:04 AM net.sourceforge.ganttproject.GPLogger log
INFOS: [ProgressMonitorImpl] begin subTask: name=Export project
avr. 25, 2018 10:58:04 AM net.sourceforge.ganttproject.GPLogger logToLogger
AVERTISSEMENT: Export failure. Failed subtask: Export project
java.lang.RuntimeException: Export failure. Failed subtask: Export project
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:167)
	at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile.createProjectWriter(ExporterToMsProjectFile.java:143)
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile.access$100(ExporterToMsProjectFile.java:46)
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile$2.run(ExporterToMsProjectFile.java:119)
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:165)
	... 2 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at org.bardsoftware.impl.eclipsito.BundleClassLoader.findClass(BundleClassLoader.java:131)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 more



!!!!!!!!!!! canceling family=Export job family


cleaning jobs...
wn Source)
	at java.xml/javax.xml.parsers.SAXParser.parse(Unknown Source)
	at net.sourceforge.ganttproject.io.XmlParser.parse(XmlParser.java:110)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.doLoad(GanttXMLOpen.java:102)
	at net.sourceforge.ganttproject.io.GanttXMLOpen.load(GanttXMLOpen.java:96)
	at net.sourceforge.ganttproject.document.ProxyDocument$ParsingState.enter(ProxyDocument.java:360)
	at net.sourceforge.ganttproject.document.ProxyDocument.read(ProxyDocument.java:178)
	at net.sourceforge.ganttproject.GanttProject.open(GanttProject.java:689)
	at net.sourceforge.ganttproject.gui.ProjectOpenStrategy.openFileAsIs(ProjectOpenStrategy.java:119)
	at net.sourceforge.ganttproject.gui.ProjectUIFacadeImpl.openProject(ProjectUIFacadeImpl.java:248)
	at net.sourceforge.ganttproject.action.project.OpenMRUDocumentAction.actionPerformed(OpenMRUDocumentAction.java:66)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

avr. 25, 2018 10:58:04 AM net.sourceforge.ganttproject.GPLogger log
INFOS: [ProgressMonitorImpl] begin Task: name=Running export
avr. 25, 2018 10:58:04 AM net.sourceforge.ganttproject.GPLogger log
INFOS: [ProgressMonitorImpl] begin subTask: name=Export project
avr. 25, 2018 10:58:04 AM net.sourceforge.ganttproject.GPLogger logToLogger
AVERTISSEMENT: Export failure. Failed subtask: Export project
java.lang.RuntimeException: Export failure. Failed subtask: Export project
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:167)
	at org.bardsoftware.impl.eclipsito.JobManagerImpl$GroupWorker.run(JobManagerImpl.java:163)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile.createProjectWriter(ExporterToMsProjectFile.java:143)
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile.access$100(ExporterToMsProjectFile.java:46)
	at biz.ganttproject.impex.msproject2.ExporterToMsProjectFile$2.run(ExporterToMsProjectFile.java:119)
	at net.sourceforge.ganttproject.export.ExporterBase$2.run(ExporterBase.java:165)
	... 2 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at org.bardsoftware.impl.eclipsito.BundleClassLoader.findClass(BundleClassLoader.java:131)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 more
```

**Comment by dbarashev** [comment]
Thanks for reporting! This issue is related to Java 10 modularization (and probably Java 9 as well), not to GP 2.8.7. As a workaround, you can add this line to the end of file `C:\Program Files (x86)\GanttProject-2.8\ganttproject.l4j.ini` (you can edit that file in any text editor, administrator priveleges required):

```
--add-modules java.xml.bind 
```

**Comment by lathiere** [comment]
Great: The bug is fixed.
The exported MSPDI file opens without any problem in ProjectLibre 1.7 (OpenProj).
Thank You!
Cheers.

**Comment by dbarashev** [comment]
Nope, it is not fixed. We can't ask everyone to edit ini files. These changes should be added to the distributions.
